version: '3'
networks:
  oxi_cloud_net:

services:
  db:
    image: postgres:13
    restart: always
    networks:
      - oxi_cloud_net
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: oxi_cloud_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    depends_on:
      - db
    networks:
      - oxi_cloud_net
    environment:
      DATABASE_URL: "postgres://myuser:mypassword@db/oxi_cloud_db"
    ports:
      - "8080:8080"

volumes:
  db_data:

